# Workflow runs when a matching version tag is pushed.

name: Publish File Service NuGet Package

on:
  push:
    tags: [fs/v*]
  workflow_dispatch:

jobs:
  publish-file-service-nuget-package:
    # ↓ Change this to "false" to disable the workflow without any alert messages.
    if: ${{ true }}
    # ↑ Change to "true" (or delete) to enable the workflow.

    name: Publish File Service NuGet package
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Build and pack
        run: dotnet build --configuration Release

      - name: NuGet Push
        run: dotnet nuget push .artifacts/FileService/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
